#jasypt:
#  encryptor:
#    password: Datarse_PAmaster
#    bean: jasyptStringEncryptor

# jwt:
#  secret: jwtsecret        

# TODO: secret key 변경적용
# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용 (아래 명령어를 터미널에 쳐보면 그대로 나옴)
# $ echo 'spring-boot-security-jwt-tutorial-jiwoon-spring-boot-security-jwt-tutorial' | base64
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK  

server:
  port: 9000

front:
  host:
    url: http://localhost:5000

#mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
    level:
        org:
            springframework:
                web: DEBUG
                security: DEBUG
            hibernate:
              event:
                internal: ERROR
              engine:
                internal: ERROR
        com:
          zaxxer:
            hikari:
              pool:
                PoolBase: ERROR
                HikariPool: ERROR
              HikariDataSource: ERROR

